### ISSUE TITLE
Do you have thoughts on adding a CLI?

### ISSUE THREAD

**Issue by arturoromeroslc** [Nike-Inc/bokor#13]
Great tool.

I was thinking if there is thought or a roadmap to add a cli for Bokor.
The simple use case that is would solve would be not needing a seperate `bokor/index.js` file, when using bokor whenever using a "default" scructure. 

In an app you need to start the dev server (typically) and then start the bokor server which most of the time takes in default files.
i.e. `"start:bokok": "npm run start:dev && node bokor`

At some point it would be nice if we could add a cli option that would allow us to simply run
`"start:bokok": "npm run start:dev && bokor`
The cli would use default file path and names unless args to overwrite some of those values was passed in.

**Comment by jimmyeisenhauer** [comment]
I really don't have any plans for bokor at this time.  It is currently meeting all my needs.  However I would be receptive to taking it in any direction as long as it continues to meet its current needs.  

I find the idea interesting but I always find a need for a custom filter perhaps others out there don't.

**Comment by jimmyeisenhauer** [comment]
added cli!
